services:
  ros:
    build: .
    ports:
      - "8765:8765"
    privileged: true
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./ws:/root/ws
    working_dir: /root/ws
    command: bash -c "echo 'source /opt/ros/humble/setup.bash' >> ~/.bashrc && bash"